#!/usr/bin/env bash
set -Eeuo pipefail

PROGRAM_NAME="$(basename "$0")"
TARGET_RELATIVE="publication/site"
FORCE=0
SKIP_INSTALL=0

usage() {
  cat <<'USAGE'
Bootstrap the Monad documentation publication site.

Usage:
  bootstrap-monad-docs-site.sh [options]

Options:
  --force         Overwrite files owned by this bootstrap script.
                  Unknown files are preserved.
  --skip-install  Create the scaffold without running bun install/typecheck.
  --target PATH   Override the target path relative to the repository root.
  -h, --help      Show this help text.

Environment:
  MONAD_ROOT      Explicit repository root. Otherwise git root or cwd is used.
USAGE
}

log() {
  printf '[%s] %s\n' "$PROGRAM_NAME" "$*"
}

fail() {
  printf '[%s] error: %s\n' "$PROGRAM_NAME" "$*" >&2
  exit 1
}

while (($# > 0)); do
  case "$1" in
    --force)
      FORCE=1
      shift
      ;;
    --skip-install)
      SKIP_INSTALL=1
      shift
      ;;
    --target)
      (($# >= 2)) || fail "--target requires a path"
      TARGET_RELATIVE="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      fail "unknown option: $1"
      ;;
  esac
done

if [[ -n "${MONAD_ROOT:-}" ]]; then
  REPO_ROOT="$(cd "$MONAD_ROOT" && pwd)"
elif git_root="$(git rev-parse --show-toplevel 2>/dev/null)"; then
  REPO_ROOT="$git_root"
else
  REPO_ROOT="$(pwd)"
fi

TARGET="$REPO_ROOT/$TARGET_RELATIVE"
MARKER="$TARGET/.monad-site-bootstrap"

if [[ -d "$TARGET" && ! -f "$MARKER" && $FORCE -ne 1 ]]; then
  fail "$TARGET already exists and is not marked as bootstrap-owned; rerun with --force only after reviewing it"
fi

mkdir -p \
  "$TARGET/app/api/search" \
  "$TARGET/app/system/[[...slug]]" \
  "$TARGET/components" \
  "$TARGET/content/system" \
  "$TARGET/lib" \
  "$TARGET/public" \
  "$TARGET/styles"

write_file() {
  local relative="$1"
  local destination="$TARGET/$relative"
  mkdir -p "$(dirname "$destination")"

  if [[ -e "$destination" && $FORCE -ne 1 ]]; then
    log "preserving existing $relative"
    cat >/dev/null
    return
  fi

  cat >"$destination"
  log "wrote $relative"
}

write_file ".monad-site-bootstrap" <<'EOF'
SITE-0001
This marker identifies files created by tools/bootstrap-monad-docs-site.sh.
EOF

write_file ".gitignore" <<'EOF'
# dependencies
node_modules/

# Next.js
.next/
out/

# Fumadocs generated source
.source/

# local environment
.env
.env.*
!.env.example

# local tooling
*.log
.DS_Store
EOF

write_file "package.json" <<'EOF'
{
  "name": "@monad/publication-site",
  "version": "0.1.0",
  "private": true,
  "description": "The documentation and engineering-log publication site for Monad.",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "typecheck": "tsc --noEmit"
  },
  "engines": {
    "node": ">=20.9.0"
  },
  "dependencies": {
    "fumadocs-core": "16.14.0",
    "fumadocs-mdx": "15.2.2",
    "fumadocs-ui": "16.14.0",
    "next": "16.3.0",
    "react": "19.2.8",
    "react-dom": "19.2.8"
  },
  "devDependencies": {
    "@tailwindcss/postcss": "4.2.0",
    "@types/mdx": "2.0.13",
    "@types/node": "^24.0.0",
    "@types/react": "19.2.14",
    "@types/react-dom": "^19.2.3",
    "postcss": "^8.5.6",
    "tailwindcss": "4.2.0",
    "typescript": "^5.9.3"
  }
}
EOF

write_file "tsconfig.json" <<'EOF'
{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts",
    ".source/**/*.ts"
  ],
  "exclude": ["node_modules"]
}
EOF

write_file "next-env.d.ts" <<'EOF'
/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js conventions and should not be edited manually.
EOF

write_file "next.config.mjs" <<'EOF'
import { createMDX } from 'fumadocs-mdx/next';

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

const withMDX = createMDX();

export default withMDX(nextConfig);
EOF

write_file "postcss.config.mjs" <<'EOF'
/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    '@tailwindcss/postcss': {},
  },
};

export default config;
EOF

write_file "app/global.css" <<'EOF'
@import 'tailwindcss';
@import 'fumadocs-ui/css/neutral.css';
@import 'fumadocs-ui/css/preset.css';

:root {
  --monad-content-max: 76rem;
}

html {
  scroll-behavior: smooth;
}

body {
  min-height: 100vh;
  background:
    radial-gradient(circle at top, color-mix(in oklab, var(--color-fd-primary) 7%, transparent), transparent 34rem),
    var(--color-fd-background);
}

::selection {
  background: color-mix(in oklab, var(--color-fd-primary) 28%, transparent);
}
EOF

write_file "app/layout.tsx" <<'EOF'
import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import { RootProvider } from 'fumadocs-ui/provider/next';
import './global.css';

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'http://localhost:3000';

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: 'Monad Engineering Log',
    template: '%s · Monad Engineering Log',
  },
  description:
    'The architecture, decisions, specifications, implementation history, and engineering narrative of Monad.',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="flex min-h-screen flex-col font-sans antialiased">
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
EOF

write_file "app/page.tsx" <<'EOF'
import Link from 'next/link';

const sections = [
  {
    href: '/system',
    eyebrow: 'Reference path',
    title: 'Understand Monad',
    description:
      'Explore the system model, architecture, components, constraints, and technical vocabulary.',
  },
  {
    href: '/system/publication-architecture',
    eyebrow: 'Implementation record',
    title: 'Publication architecture',
    description:
      'See how canonical repository documents become routes, search data, and future derived editions.',
  },
];

export default function HomePage() {
  return (
    <main className="mx-auto flex w-full max-w-[var(--monad-content-max)] flex-1 flex-col px-6 py-16 lg:px-10 lg:py-24">
      <div className="max-w-4xl">
        <p className="mb-5 font-mono text-sm tracking-[0.18em] text-fd-muted-foreground uppercase">
          Monad Engineering Log
        </p>
        <h1 className="text-balance text-5xl font-semibold tracking-[-0.04em] sm:text-7xl">
          Building Monad in public, with the reasoning intact.
        </h1>
        <p className="mt-7 max-w-3xl text-pretty text-lg leading-8 text-fd-muted-foreground sm:text-xl">
          A durable technical publication for Monad&apos;s engineering journal,
          architecture, specifications, decisions, experiments, and implementation history.
        </p>
      </div>

      <div className="mt-14 grid gap-5 md:grid-cols-2">
        {sections.map((section) => (
          <Link
            key={section.href}
            href={section.href}
            className="group rounded-2xl border bg-fd-card p-7 transition hover:-translate-y-0.5 hover:border-fd-primary/50 hover:shadow-lg"
          >
            <p className="font-mono text-xs tracking-[0.16em] text-fd-muted-foreground uppercase">
              {section.eyebrow}
            </p>
            <h2 className="mt-3 text-2xl font-semibold tracking-tight group-hover:text-fd-primary">
              {section.title}
            </h2>
            <p className="mt-3 leading-7 text-fd-muted-foreground">
              {section.description}
            </p>
          </Link>
        ))}
      </div>

      <footer className="mt-auto pt-20 text-sm text-fd-muted-foreground">
        SITE-0001 · Documentation foundation
      </footer>
    </main>
  );
}
EOF

write_file "components/mdx.tsx" <<'EOF'
import defaultMdxComponents from 'fumadocs-ui/mdx';
import type { MDXComponents } from 'mdx/types';

export function getMDXComponents(components?: MDXComponents) {
  return {
    ...defaultMdxComponents,
    ...components,
  } satisfies MDXComponents;
}

export const useMDXComponents = getMDXComponents;

declare global {
  type MDXProvidedComponents = ReturnType<typeof getMDXComponents>;
}
EOF

write_file "lib/layout.shared.tsx" <<'EOF'
import type { BaseLayoutProps } from 'fumadocs-ui/layouts/shared';

export function baseOptions(): BaseLayoutProps {
  return {
    nav: {
      title: (
        <span className="flex items-baseline gap-2">
          <span className="font-semibold">Monad</span>
          <span className="hidden font-mono text-xs text-fd-muted-foreground sm:inline">
            Engineering Log
          </span>
        </span>
      ),
    },
    links: [
      {
        text: 'System',
        url: '/system',
        active: 'nested-url',
      },
    ],
  };
}
EOF

write_file "lib/source.ts" <<'EOF'
import { loader } from 'fumadocs-core/source';
import { defineDocs } from 'fumadocs-mdx/macro';

const systemDocs = defineDocs({
  dir: 'content/system',
});

export const systemSource = loader({
  baseUrl: '/system',
  source: systemDocs.toFumadocsSource(),
});
EOF

write_file "app/system/layout.tsx" <<'EOF'
import type { ReactNode } from 'react';
import { DocsLayout } from 'fumadocs-ui/layouts/docs';
import { baseOptions } from '@/lib/layout.shared';
import { systemSource } from '@/lib/source';

export default function SystemLayout({ children }: { children: ReactNode }) {
  return (
    <DocsLayout tree={systemSource.pageTree} {...baseOptions()}>
      {children}
    </DocsLayout>
  );
}
EOF

write_file "app/system/[[...slug]]/page.tsx" <<'EOF'
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import {
  DocsBody,
  DocsDescription,
  DocsPage,
  DocsTitle,
} from 'fumadocs-ui/page';
import { getMDXComponents } from '@/components/mdx';
import { systemSource } from '@/lib/source';

type PageProps = {
  params: Promise<{ slug?: string[] }>;
};

export default async function SystemPage({ params }: PageProps) {
  const { slug } = await params;
  const page = systemSource.getPage(slug);

  if (!page) notFound();

  const MDX = page.data.body;

  return (
    <DocsPage toc={page.data.toc} full={page.data.full}>
      <DocsTitle>{page.data.title}</DocsTitle>
      <DocsDescription>{page.data.description}</DocsDescription>
      <DocsBody>
        <MDX components={getMDXComponents()} />
      </DocsBody>
    </DocsPage>
  );
}

export function generateStaticParams() {
  return systemSource.generateParams();
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const page = systemSource.getPage(slug);

  if (!page) notFound();

  return {
    title: page.data.title,
    description: page.data.description,
  };
}
EOF

write_file "app/api/search/route.ts" <<'EOF'
import { createFromSource } from 'fumadocs-core/search/server';
import { systemSource } from '@/lib/source';

export const { GET } = createFromSource(systemSource);
EOF

write_file "content/system/meta.json" <<'EOF'
{
  "title": "System",
  "pages": ["index", "publication-architecture"]
}
EOF

write_file "content/system/index.mdx" <<'EOF'
---
title: Understand Monad
description: The stable reference path through Monad's architecture, concepts, components, and operating model.
---

# Understand Monad

This section is the reference-oriented counterpart to the chronological **Building Monad** engineering narrative.

## What belongs here

- Stable system concepts and vocabulary
- Architecture views and component boundaries
- Runtime, state, lifecycle, and workflow models
- Security, governance, and operational constraints
- Links to the specifications and decisions that establish each claim

## What does not belong here

Development chronology, failed experiments, and day-by-day reasoning belong in the Building Monad series and project build log. This section presents the clearest current model of the system.

<Callout title="SITE-0001 boundary">
  The two pages currently in this collection are bootstrap content. SITE-0003 will ingest canonical documents from the repository rather than treating this directory as their permanent source of truth.
</Callout>
EOF

write_file "content/system/publication-architecture.mdx" <<'EOF'
---
title: Publication Architecture
description: The boundary between canonical Monad documents and their rendered publication forms.
---

# Publication architecture

The documentation application is a renderer and presentation system. It is **not** the canonical home of Monad's engineering records.

## Source boundary

```text
Canonical repository documents
  journal/  architecture/  adrs/  specifications/
  engineering/  research/  knowledge/  build-log/
                         │
                         ▼
             content discovery adapter
                         │
                         ▼
        normalized metadata + relationship graph
                         │
             ┌───────────┼───────────┐
             ▼           ▼           ▼
          website      search      derived editions
```

## Current bootstrap stage

SITE-0001 establishes the application shell and proves that Fumadocs, Next.js, MDX rendering, page-tree generation, and search can operate inside `publication/site/`.

The canonical-corpus adapter is intentionally deferred until SITE-0003 so that ingestion rules are designed explicitly rather than hidden inside framework conventions.
EOF

write_file "ARCHITECTURE.md" <<'EOF'
# Monad Publication Site Architecture

**Work packet:** SITE-0001 of 12  
**Status:** Foundation  
**Application root:** `publication/site/`

## Decision

Use Next.js 16, React 19, Fumadocs Core/UI/MDX, Tailwind CSS 4, TypeScript, and Bun.

## Architectural boundary

The publication application renders and indexes canonical Monad documents, but it does not own them. The canonical corpus remains in the repository's domain-oriented directories, including `journal/`, `architecture/`, `adrs/`, `specifications/`, `engineering/`, `research/`, `knowledge/`, and `build-log/`.

Bootstrap MDX under `content/system/` exists only to keep the site independently runnable before the repository ingestion adapter is implemented in SITE-0003.

## Initial route contract

| Route | Purpose | State |
|---|---|---|
| `/` | Publication landing page | Implemented |
| `/system` | Stable system-reference path | Implemented |
| `/api/search` | Fumadocs search endpoint | Implemented |
| `/building-monad` | Chronological engineering narrative | Reserved |
| `/artifacts` | Specifications, ADRs, research, and records | Reserved |
| `/project` | Status, roadmap, releases, and build log | Reserved |

## Non-goals for SITE-0001

- Importing the external canonical corpus
- Final visual identity
- Artifact relationship graphs
- Versioned publication editions
- PDF, EPUB, RSS, `llms.txt`, or offline outputs
- Production deployment configuration

## Next implementation packet

SITE-0002 will harden the application foundation: shared configuration, route groups, error states, testing baseline, developer tooling, and the first reusable Monad UI primitives.
EOF

write_file "README.md" <<'EOF'
# Monad Publication Site

Fumadocs-powered documentation and engineering-log publication application for Monad.

## Requirements

- Node.js 20.9 or newer
- Bun

## Local development

```bash
bun install
bun run dev
```

Open `http://localhost:3000`.

## Verification

```bash
bun run typecheck
bun run build
```

## Content boundary

The MDX files under `content/system/` are bootstrap fixtures. Canonical Monad documents remain outside this application and will be consumed through the SITE-0003 ingestion adapter.

See [`ARCHITECTURE.md`](./ARCHITECTURE.md) for the current route and ownership decisions.
EOF

if [[ $SKIP_INSTALL -eq 1 ]]; then
  log "skipping dependency installation"
else
  command -v bun >/dev/null 2>&1 || fail "Bun is required; install Bun or rerun with --skip-install"
  log "installing dependencies"
  (
    cd "$TARGET"
    bun install
    bun run typecheck
  )
fi

log "Monad publication site scaffold is ready at $TARGET"
log "next: cd '$TARGET' && bun run dev"
